name: flutter_test_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animation_progress_bar: ^2.3.1
  flutter_bloc: ^8.1.5
  modbus_client: ^1.1.2
  modbus_client_tcp: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
